#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v12
# autospec commit: fbcebd0
#
Name     : pypi-cryptography
Version  : 42.0.7
Release  : 180
URL      : https://files.pythonhosted.org/packages/78/63/66c03eb51f0d241862083deb3f17ab5fce08cf6b347db7887bcb4d1a194e/cryptography-42.0.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/78/63/66c03eb51f0d241862083deb3f17ab5fce08cf6b347db7887bcb4d1a194e/cryptography-42.0.7.tar.gz
Source1  : http://localhost/cgit/vendor/pypi-cryptography/snapshot/pypi-cryptography-2024-05-26-18-25-12.tar.xz
Summary  : cryptography is a package which provides cryptographic recipes and primitives to Python developers.
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT
Requires: pypi-cryptography-license = %{version}-%{release}
Requires: pypi-cryptography-python = %{version}-%{release}
Requires: pypi-cryptography-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
pyca/cryptography
=================
.. image:: https://img.shields.io/pypi/v/cryptography.svg
:target: https://pypi.org/project/cryptography/
:alt: Latest Version

%package license
Summary: license components for the pypi-cryptography package.
Group: Default

%description license
license components for the pypi-cryptography package.


%package python
Summary: python components for the pypi-cryptography package.
Group: Default
Requires: pypi-cryptography-python3 = %{version}-%{release}

%description python
python components for the pypi-cryptography package.


%package python3
Summary: python3 components for the pypi-cryptography package.
Group: Default
Requires: python3-core
Requires: pypi(cffi)
Requires: pypi(six)

%description python3
python3 components for the pypi-cryptography package.


%prep
%setup -q -n cryptography-42.0.7
cd %{_builddir}
tar xf %{_sourcedir}/pypi-cryptography-2024-05-26-18-25-12.tar.xz
cd %{_builddir}/cryptography-42.0.7
mkdir -p ./vendor
cp -r %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/* %{_builddir}/cryptography-42.0.7/./vendor
mkdir -p .cargo
echo '[source.crates-io]' >> .cargo/config.toml
echo 'replace-with = "vendored-sources"' >> .cargo/config.toml
echo '[source.vendored-sources]' >> .cargo/config.toml
echo 'directory = "vendor"' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1717167126
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-cryptography
cp %{_builddir}/cryptography-%{version}/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/de33ead2bee64352544ce0aa9e410c0c44fdf7d9 || :
cp %{_builddir}/cryptography-%{version}/LICENSE.BSD %{buildroot}/usr/share/package-licenses/pypi-cryptography/ea5b412c09f3b29ba1d81a61b878c5c16ffe69d8 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/aead/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/78759038583c01b9b43a0295d66f6f07f1ae45fb || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/aead/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/00abd4963494431e3c1bb44b0fb15934c8a9a21c || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/aes-gcm-siv/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/aes-gcm-siv/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/538b8b17dcc71bfd00cb16b15cb75be91c617bca || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/aes/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/aes/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/d4fd358c142c0ce7553ff8266b871bae99e3052c || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/cipher/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/cipher/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/708e756c9120bcaf2c0a1d240b2418ee908e2d87 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/cpufeatures/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/cpufeatures/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/388871ab0ab7f8ba6aaa0d444a5153f15c918cdb || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/crypto-common/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/crypto-common/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/7ca2c807379211b3ca6b04f10723088ca423c4fe || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/ctr/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/ctr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/f42d34de86fd6d6a78f509b43b3f3db60d1d1cdf || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/generic-array/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cryptography/cb74eb831db08b7fe98f84b59c9bda195e5a3588 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/c8eef3d34d69b1d62fd378fa02150a0bce62fd26 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/hex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/hex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/b916da18877fcec3d37860fe60c1189c447e90b9 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/inout/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/inout/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/e03b48c8e0c3b1ab53f81d9913b997d6c82b4829 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/opaque-debug/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/opaque-debug/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/ff86155689d8084be1a512c19b9f3b78e2322132 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/polyval/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/polyval/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/f804c884680732dd357a79d4d69edd7a3485e667 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/rand_core/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-cryptography/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/rand_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/subtle/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cryptography/145c27c874c444c902ad2af6164fcc30231fa7a8 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/typenum/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cryptography/481e4be7d70c11ee3f6e04a59a0e5afccc551db2 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/typenum/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/69facfd64b2a7aa4a22c917ef10cd96e41b75b87 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/typenum/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/5984f5244c7bc13bf15a5bea823c04ec0bbc714f || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/universal-hash/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/universal-hash/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/3010a4acf57cd798a69a1011980b53d84dbcd06a || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/version_check/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/version_check/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/cfcb552ef0afbe7ccb4128891c0de00685988a4b || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/wasi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/wasi/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/pypi-cryptography/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/wasi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/zeroize/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/pypi-cryptography-2024-05-26-18-25-12/zeroize/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/f24fdeaeee4c59532e32b7c6517d34c8927526fe || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-cryptography/00abd4963494431e3c1bb44b0fb15934c8a9a21c
/usr/share/package-licenses/pypi-cryptography/145c27c874c444c902ad2af6164fcc30231fa7a8
/usr/share/package-licenses/pypi-cryptography/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/pypi-cryptography/3010a4acf57cd798a69a1011980b53d84dbcd06a
/usr/share/package-licenses/pypi-cryptography/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/pypi-cryptography/388871ab0ab7f8ba6aaa0d444a5153f15c918cdb
/usr/share/package-licenses/pypi-cryptography/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/pypi-cryptography/422e6fd980775f9997ed6735c28a14ad20c222e8
/usr/share/package-licenses/pypi-cryptography/481e4be7d70c11ee3f6e04a59a0e5afccc551db2
/usr/share/package-licenses/pypi-cryptography/538b8b17dcc71bfd00cb16b15cb75be91c617bca
/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/pypi-cryptography/5984f5244c7bc13bf15a5bea823c04ec0bbc714f
/usr/share/package-licenses/pypi-cryptography/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/pypi-cryptography/69facfd64b2a7aa4a22c917ef10cd96e41b75b87
/usr/share/package-licenses/pypi-cryptography/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/pypi-cryptography/708e756c9120bcaf2c0a1d240b2418ee908e2d87
/usr/share/package-licenses/pypi-cryptography/78759038583c01b9b43a0295d66f6f07f1ae45fb
/usr/share/package-licenses/pypi-cryptography/7ca2c807379211b3ca6b04f10723088ca423c4fe
/usr/share/package-licenses/pypi-cryptography/b916da18877fcec3d37860fe60c1189c447e90b9
/usr/share/package-licenses/pypi-cryptography/c8eef3d34d69b1d62fd378fa02150a0bce62fd26
/usr/share/package-licenses/pypi-cryptography/cb74eb831db08b7fe98f84b59c9bda195e5a3588
/usr/share/package-licenses/pypi-cryptography/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/pypi-cryptography/cfcb552ef0afbe7ccb4128891c0de00685988a4b
/usr/share/package-licenses/pypi-cryptography/d4fd358c142c0ce7553ff8266b871bae99e3052c
/usr/share/package-licenses/pypi-cryptography/d74ad13f1402c35008f22bc588a6b8199ed164d3
/usr/share/package-licenses/pypi-cryptography/de33ead2bee64352544ce0aa9e410c0c44fdf7d9
/usr/share/package-licenses/pypi-cryptography/e03b48c8e0c3b1ab53f81d9913b997d6c82b4829
/usr/share/package-licenses/pypi-cryptography/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/pypi-cryptography/ea5b412c09f3b29ba1d81a61b878c5c16ffe69d8
/usr/share/package-licenses/pypi-cryptography/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/pypi-cryptography/f14afa20edce530124d39cd56312c7781c19b267
/usr/share/package-licenses/pypi-cryptography/f24fdeaeee4c59532e32b7c6517d34c8927526fe
/usr/share/package-licenses/pypi-cryptography/f42d34de86fd6d6a78f509b43b3f3db60d1d1cdf
/usr/share/package-licenses/pypi-cryptography/f804c884680732dd357a79d4d69edd7a3485e667
/usr/share/package-licenses/pypi-cryptography/ff86155689d8084be1a512c19b9f3b78e2322132

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
