#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v2
# autospec commit: 250a666
#
Name     : pypi-cryptography
Version  : 41.0.5
Release  : 176
URL      : https://files.pythonhosted.org/packages/16/a7/38fdcdd634515f589c8c723608c0f0b38d66c6c2320b3095967486f3045a/cryptography-41.0.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/16/a7/38fdcdd634515f589c8c723608c0f0b38d66c6c2320b3095967486f3045a/cryptography-41.0.5.tar.gz
Source1  : http://localhost/cgit/projects/cryptography-vendor/snapshot/cryptography-vendor-41.0.4.tar.xz
Summary  : cryptography is a package which provides cryptographic recipes and primitives to Python developers.
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT Unicode-DFS-2016
Requires: pypi-cryptography-license = %{version}-%{release}
Requires: pypi-cryptography-python = %{version}-%{release}
Requires: pypi-cryptography-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pkgconfig(openssl)
BuildRequires : pypi(cffi)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_rust)
BuildRequires : pypi(wheel)
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
pyca/cryptography
=================
.. image:: https://img.shields.io/pypi/v/cryptography.svg
:target: https://pypi.org/project/cryptography/
:alt: Latest Version

%package license
Summary: license components for the pypi-cryptography package.
Group: Default

%description license
license components for the pypi-cryptography package.


%package python
Summary: python components for the pypi-cryptography package.
Group: Default
Requires: pypi-cryptography-python3 = %{version}-%{release}

%description python
python components for the pypi-cryptography package.


%package python3
Summary: python3 components for the pypi-cryptography package.
Group: Default
Requires: python3-core
Provides: pypi(cryptography)
Requires: pypi(cffi)
Requires: pypi(six)

%description python3
python3 components for the pypi-cryptography package.


%prep
%setup -q -n cryptography-41.0.5
cd %{_builddir}
tar xf %{_sourcedir}/cryptography-vendor-41.0.4.tar.xz
cd %{_builddir}/cryptography-41.0.5
mkdir -p ./
cp -r %{_builddir}/cryptography-vendor-41.0.4/* %{_builddir}/cryptography-41.0.5/./
pushd ..
cp -a cryptography-41.0.5 buildavx2
popd

%build
## build_prepend_once content
mkdir -p $HOME/.cargo
cat > $HOME/.cargo/config.toml << "EOF"
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF
ln -s $PWD/vendor $HOME/vendor
## build_prepend_once end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1698167004
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-cryptography
cp %{_builddir}/cryptography-%{version}/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/de33ead2bee64352544ce0aa9e410c0c44fdf7d9 || :
cp %{_builddir}/cryptography-%{version}/LICENSE.BSD %{buildroot}/usr/share/package-licenses/pypi-cryptography/ea5b412c09f3b29ba1d81a61b878c5c16ffe69d8 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/aliasable/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5f2da41389ce5873a46945bc1b75454acfd75cf6 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/asn1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cryptography/b9b8e747d9af5285e3cf6852d84ec355b39c70e8 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/asn1_derive/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cryptography/b9b8e747d9af5285e3cf6852d84ec355b39c70e8 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/base64/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/base64/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/cc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/cc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/foreign-types-shared/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/foreign-types-shared/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/bee28506691ec4e9291da8a55a450cb5304d3f5d || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/foreign-types/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/foreign-types/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/bee28506691ec4e9291da8a55a450cb5304d3f5d || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/indoc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/indoc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cryptography/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/openssl-macros/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/openssl-macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/245c1d51cca7faae2e37a0e0c681efb8aa42bccf || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/openssl-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/openssl/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cryptography/ffd5a0caea8a089d58fb6acf5a4714dffb06d0dc || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/ouroboros/LICENSE_APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/97217ef49a087b476f6a7a16bb79c743492786e3 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/ouroboros/LICENSE_MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/5f0a6236f4e77988d403a2ff7465671427fa267f || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/ouroboros_macro/LICENSE_APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/97217ef49a087b476f6a7a16bb79c743492786e3 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/ouroboros_macro/LICENSE_MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/5f0a6236f4e77988d403a2ff7465671427fa267f || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/parking_lot/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/parking_lot/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/parking_lot_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/parking_lot_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/pem/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-cryptography/62130e917677e059de5fb38e7bfdd72f299bb1f8 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/pkg-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/pkg-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/proc-macro-error-attr/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/a88eaffea57a51eedb5291e0d55a959df7659458 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/proc-macro-error-attr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/655a437377cc2780990746fe2492fa16764df083 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/proc-macro-error/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/197cb40dc96ded1e036d13ef67fdc7a758ca1388 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/proc-macro-error/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/655a437377cc2780990746fe2492fa16764df083 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/pyo3-build-config/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/pyo3-macros-backend/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/pyo3-macros/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/pyo3/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cryptography/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/syn-1.0.109/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/syn-1.0.109/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/target-lexicon/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cryptography/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/pypi-cryptography/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/unindent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/unindent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/vcpkg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/f85f58f2b17e35a1c2fd852cd58e5bae165ebea9 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/vcpkg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/3ede8a2ceb97cd197183b1a9d7958b57cea01e14 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/version_check/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/version_check/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-cryptography/cfcb552ef0afbe7ccb4128891c0de00685988a4b || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows-sys/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-cryptography/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows-sys/license-mit %{buildroot}/usr/share/package-licenses/pypi-cryptography/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-cryptography/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/pypi-cryptography/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-cryptography/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-cryptography/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-cryptography/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-cryptography/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-cryptography/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-cryptography/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-cryptography/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-cryptography/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-cryptography/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-cryptography/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-cryptography/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-cryptography/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-cryptography/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cryptography-vendor-41.0.4/vendor/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-cryptography/689ec0681815ecc32bee639c68e7740add7bd301 || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-cryptography/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/pypi-cryptography/197cb40dc96ded1e036d13ef67fdc7a758ca1388
/usr/share/package-licenses/pypi-cryptography/245c1d51cca7faae2e37a0e0c681efb8aa42bccf
/usr/share/package-licenses/pypi-cryptography/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/pypi-cryptography/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/pypi-cryptography/3ede8a2ceb97cd197183b1a9d7958b57cea01e14
/usr/share/package-licenses/pypi-cryptography/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/pypi-cryptography/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/pypi-cryptography/5bb5828e544f63bd76c1b7112981a1ad86ae77f9
/usr/share/package-licenses/pypi-cryptography/5f0a6236f4e77988d403a2ff7465671427fa267f
/usr/share/package-licenses/pypi-cryptography/5f2da41389ce5873a46945bc1b75454acfd75cf6
/usr/share/package-licenses/pypi-cryptography/62130e917677e059de5fb38e7bfdd72f299bb1f8
/usr/share/package-licenses/pypi-cryptography/655a437377cc2780990746fe2492fa16764df083
/usr/share/package-licenses/pypi-cryptography/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/pypi-cryptography/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/pypi-cryptography/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/pypi-cryptography/97217ef49a087b476f6a7a16bb79c743492786e3
/usr/share/package-licenses/pypi-cryptography/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/pypi-cryptography/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/pypi-cryptography/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/pypi-cryptography/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/pypi-cryptography/a88eaffea57a51eedb5291e0d55a959df7659458
/usr/share/package-licenses/pypi-cryptography/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2
/usr/share/package-licenses/pypi-cryptography/b9b8e747d9af5285e3cf6852d84ec355b39c70e8
/usr/share/package-licenses/pypi-cryptography/bee28506691ec4e9291da8a55a450cb5304d3f5d
/usr/share/package-licenses/pypi-cryptography/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/pypi-cryptography/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/pypi-cryptography/cfcb552ef0afbe7ccb4128891c0de00685988a4b
/usr/share/package-licenses/pypi-cryptography/de33ead2bee64352544ce0aa9e410c0c44fdf7d9
/usr/share/package-licenses/pypi-cryptography/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/pypi-cryptography/ea5b412c09f3b29ba1d81a61b878c5c16ffe69d8
/usr/share/package-licenses/pypi-cryptography/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/pypi-cryptography/f498d95a48889a0b1432e420e6754881eff1d593
/usr/share/package-licenses/pypi-cryptography/f85f58f2b17e35a1c2fd852cd58e5bae165ebea9
/usr/share/package-licenses/pypi-cryptography/ffd5a0caea8a089d58fb6acf5a4714dffb06d0dc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
